# Copyright (C) 2025 Bang & Olufsen A/S, Denmark
#
# SPDX-License-Identifier: GPL-2.0-or-later

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:
    timeout: 30s
  
  reduceresolution:
  

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch, reduceresolution]
      exporters: [debug]
